title: Gnosis Center
description: Pursuit of the truth hidden behind this material realm.
url: https://cybercying.github.io
baseurl: /doc
remote_theme: mmistakes/minimal-mistakes@4.27.1
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-titles-from-headings
  - jemoji

relative_links:
  enabled: true
  collections: true

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

titles_from_headings:
  strip_title: true

defaults:
  -
    scope:
      path: "/gnosis/ai_chat/*" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
      toc: true
      toc_sticky: true
      sidebar:
        nav: "ai_chat"
  -
    scope:
      path: "/gnosis/The_Architect_of_Struggle*"
      type: pages
    values:
      layout: page
      toc: true
      toc_sticky: true
      sidebar:
        nav: "docs"


