title: Gnosis Center
description: Pursuit of the truth hidden behind this material realm.
url: cybercying.github.io
baseurl: /doc
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true
