title: Gnosis Center
description: Pursuit of the truth hidden behind this material realm.
url: https://cybercying.github.io
baseurl: /doc
remote_theme: mmistakes/minimal-mistakes@4.27.1
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

titles_from_headings:
  strip_title: true
